import { create } from 'zustand';

export const useKYCStore = create((set) => ({
  step: 1,
  documentType: null,
  idNumber: '',
  issueDate: '',
  expiryDate: '',
  frontFile: null,
  backFile: null,
  frontProgress: 0,
  backProgress: 0,
  frontUploaded: false,
  backUploaded: false,
  selfieUploaded: false,
  selfieImage: null,
  
  setStep: (step) => set({ step }),
  setDocumentType: (documentType) => set({ documentType }),
  setIdNumber: (idNumber) => set({ idNumber }),
  setIssueDate: (issueDate) => set({ issueDate }),
  setExpiryDate: (expiryDate) => set({ expiryDate }),
  setFrontFile: (frontFile) => set({ frontFile }),
  setBackFile: (backFile) => set({ backFile }),
  setFrontProgress: (frontProgress) => set({ frontProgress }),
  setBackProgress: (backProgress) => set({ backProgress }),
  setFrontUploaded: (frontUploaded) => set({ frontUploaded }),
  setBackUploaded: (backUploaded) => set({ backUploaded }),
  setSelfieUploaded: (selfieUploaded) => set({ selfieUploaded }),
  setSelfieImage: (selfieImage) => set({ selfieImage }),
}));